"""Tests for pydantic-generated schema models.

Validates that the pydantic BaseModel classes generated by schema-salad-plus-pydantic
can load and validate both Format2 and native Galaxy workflow documents.
"""

import glob
import json
import os

import pytest

from gxformat2.export import from_galaxy_native
from gxformat2.schema.gxformat2 import (
    GalaxyWorkflow,
    WorkflowStep,
)
from gxformat2.schema.native import (
    NativeGalaxyWorkflow,
    NativeInputConnection,
    NativePostJobAction,
    NativeStep,
    NativeStepType,
)
from gxformat2.yaml import ordered_load

MINIMAL_NATIVE = {
    "a_galaxy_workflow": "true",
    "format-version": "0.1",
    "name": "Minimal Test",
    "steps": {
        "0": {
            "id": 0,
            "type": "data_input",
            "name": "Input dataset",
            "label": "the_input",
            "tool_state": '{"optional": false}',
            "input_connections": {},
            "inputs": [{"name": "the_input", "description": ""}],
            "outputs": [],
            "workflow_outputs": [],
        }
    },
}

TOOL_STEP_NATIVE = {
    "a_galaxy_workflow": "true",
    "format-version": "0.1",
    "name": "Tool Step Test",
    "steps": {
        "0": {
            "id": 0,
            "type": "data_input",
            "name": "Input dataset",
            "label": "input1",
            "tool_state": '{"optional": false}',
            "input_connections": {},
            "inputs": [{"name": "input1", "description": ""}],
            "outputs": [],
            "workflow_outputs": [],
        },
        "1": {
            "id": 1,
            "type": "tool",
            "name": "Cat",
            "label": "cat_step",
            "tool_id": "cat1",
            "tool_version": "1.0.0",
            "tool_state": '{"input1": {"__class__": "ConnectedValue"}}',
            "input_connections": {"input1": {"id": 0, "output_name": "output"}},
            "inputs": [],
            "outputs": [{"name": "out_file1", "type": "input"}],
            "workflow_outputs": [{"label": "output1", "output_name": "out_file1", "uuid": None}],
            "post_job_actions": {
                "RenameDatasetActionout_file1": {
                    "action_type": "RenameDatasetAction",
                    "output_name": "out_file1",
                    "action_arguments": {"newname": "renamed_output"},
                }
            },
        },
    },
}

BASIC_FORMAT2 = """
class: GalaxyWorkflow
label: simple workflow
inputs:
  the_input:
    type: data
steps:
  the_step:
    tool_id: cat1
    in:
      input1: the_input
outputs:
  the_output:
    outputSource: the_step/out_file1
"""


class TestNativePydantic:

    def test_minimal_workflow(self):
        wf = NativeGalaxyWorkflow.model_validate(MINIMAL_NATIVE)
        assert wf.name == "Minimal Test"
        assert wf.a_galaxy_workflow == "true"
        assert wf.format_version == "0.1"

    def test_steps_are_dict(self):
        wf = NativeGalaxyWorkflow.model_validate(MINIMAL_NATIVE)
        assert isinstance(wf.steps, dict)
        assert "0" in wf.steps

    def test_step_type_enum(self):
        wf = NativeGalaxyWorkflow.model_validate(TOOL_STEP_NATIVE)
        step0 = wf.steps["0"]
        assert step0.type_ == NativeStepType.data_input
        step1 = wf.steps["1"]
        assert step1.type_ == NativeStepType.tool

    def test_input_connections(self):
        wf = NativeGalaxyWorkflow.model_validate(TOOL_STEP_NATIVE)
        step1 = wf.steps["1"]
        assert isinstance(step1.input_connections, dict)
        conn = step1.input_connections["input1"]
        assert isinstance(conn, NativeInputConnection)
        assert conn.output_name == "output"

    def test_post_job_actions(self):
        wf = NativeGalaxyWorkflow.model_validate(TOOL_STEP_NATIVE)
        step1 = wf.steps["1"]
        assert isinstance(step1.post_job_actions, dict)
        pja = step1.post_job_actions["RenameDatasetActionout_file1"]
        assert isinstance(pja, NativePostJobAction)
        assert pja.action_type == "RenameDatasetAction"
        assert pja.action_arguments == {"newname": "renamed_output"}

    def test_tool_state_string(self):
        wf = NativeGalaxyWorkflow.model_validate(MINIMAL_NATIVE)
        step = wf.steps["0"]
        assert isinstance(step.tool_state, str)

    def test_tool_state_dict(self):
        native = dict(MINIMAL_NATIVE)
        native["steps"] = {"0": dict(MINIMAL_NATIVE["steps"]["0"], tool_state={"optional": False})}
        wf = NativeGalaxyWorkflow.model_validate(native)
        step = wf.steps["0"]
        assert isinstance(step.tool_state, dict)

    def test_format_version_alias(self):
        wf = NativeGalaxyWorkflow.model_validate(MINIMAL_NATIVE)
        assert wf.format_version == "0.1"
        # Also accepts format_version directly
        alt = dict(MINIMAL_NATIVE)
        alt["format_version"] = alt.pop("format-version")
        wf2 = NativeGalaxyWorkflow.model_validate(alt)
        assert wf2.format_version == "0.1"

    def test_with_tags(self):
        wf = NativeGalaxyWorkflow.model_validate(dict(MINIMAL_NATIVE, tags=["test", "example"]))
        assert wf.tags == ["test", "example"]

    def test_with_annotation(self):
        wf = NativeGalaxyWorkflow.model_validate(dict(MINIMAL_NATIVE, annotation="A test workflow"))
        assert wf.annotation == "A test workflow"

    def test_with_comments(self):
        wf = NativeGalaxyWorkflow.model_validate(
            dict(
                MINIMAL_NATIVE,
                comments=[
                    {
                        "id": 0,
                        "type": "text",
                        "position": [100, 200],
                        "size": [200, 50],
                        "color": "none",
                        "data": {"text": "A note", "bold": False, "italic": False, "size": 1},
                    },
                    {
                        "id": 1,
                        "type": "frame",
                        "position": [0, 0],
                        "size": [500, 400],
                        "color": "blue",
                        "data": {"title": "Group"},
                        "child_steps": [0],
                        "child_comments": [],
                    },
                ],
            )
        )
        assert len(wf.comments) == 2

    def test_with_report(self):
        wf = NativeGalaxyWorkflow.model_validate(dict(MINIMAL_NATIVE, report={"markdown": "# Report\nContent."}))
        assert wf.report.markdown == "# Report\nContent."

    def test_with_source_metadata(self):
        wf = NativeGalaxyWorkflow.model_validate(
            dict(MINIMAL_NATIVE, source_metadata={"url": "https://example.com/wf.ga"})
        )
        assert wf.source_metadata.url == "https://example.com/wf.ga"

    def test_with_creator_person(self):
        wf = NativeGalaxyWorkflow.model_validate(
            dict(
                MINIMAL_NATIVE,
                creator=[{"class": "Person", "name": "Jane Doe", "identifier": "https://orcid.org/0000-0001"}],
            )
        )
        assert len(wf.creator) == 1

    def test_with_creator_organization(self):
        wf = NativeGalaxyWorkflow.model_validate(
            dict(
                MINIMAL_NATIVE,
                creator=[{"class": "Organization", "name": "Galaxy Project", "url": "https://galaxyproject.org"}],
            )
        )
        assert len(wf.creator) == 1

    def test_with_creator_mixed(self):
        wf = NativeGalaxyWorkflow.model_validate(
            dict(
                MINIMAL_NATIVE,
                creator=[
                    {"class": "Person", "name": "Jane"},
                    {"class": "Organization", "name": "Galaxy"},
                ],
            )
        )
        assert len(wf.creator) == 2

    def test_extra_fields_allowed(self):
        """Unknown fields shouldn't cause validation errors."""
        wf = NativeGalaxyWorkflow.model_validate(dict(MINIMAL_NATIVE, unknown_field="hello"))
        assert wf.name == "Minimal Test"

    def test_step_inheritance(self):
        """NativeStep should inherit from HasStepErrors, HasStepPosition, HasUUID, ReferencesTool."""
        from gxformat2.schema.native import HasStepErrors, HasStepPosition, HasUUID, ReferencesTool

        assert issubclass(NativeStep, HasStepErrors)
        assert issubclass(NativeStep, HasStepPosition)
        assert issubclass(NativeStep, HasUUID)
        assert issubclass(NativeStep, ReferencesTool)


class TestFormat2Pydantic:

    def test_basic_workflow(self):
        data = ordered_load(BASIC_FORMAT2)
        wf = GalaxyWorkflow.model_validate(data)
        assert wf.label == "simple workflow"
        assert wf.class_ == "GalaxyWorkflow"

    def test_step_type_enum(self):
        data = ordered_load(BASIC_FORMAT2)
        wf = GalaxyWorkflow.model_validate(data)
        step = wf.steps["the_step"]
        assert isinstance(step, WorkflowStep)

    def test_workflow_with_comments(self):
        data = ordered_load(BASIC_FORMAT2)
        data["comments"] = [
            {
                "type": "text",
                "position": [10, 20],
                "size": [100, 50],
                "text": "hello",
            }
        ]
        wf = GalaxyWorkflow.model_validate(data)
        assert len(wf.comments) == 1

    def test_workflow_with_creator(self):
        data = ordered_load(BASIC_FORMAT2)
        data["creator"] = [{"class": "Person", "name": "Test"}]
        wf = GalaxyWorkflow.model_validate(data)
        assert len(wf.creator) == 1

    def test_extra_fields_allowed(self):
        data = ordered_load(BASIC_FORMAT2)
        data["unknown"] = "value"
        wf = GalaxyWorkflow.model_validate(data)
        assert wf.label == "simple workflow"


# --- IWC integration tests ---

IWC_DIR = os.environ.get("GXFORMAT2_TEST_IWC_DIRECTORY")


# TODO: remove after https://github.com/galaxyproject/iwc/pull/1167 is merged
_IWC_PYDANTIC_SKIP = {
    "hic-fastq-to-cool-hicup-cooler.ga",
    "chic-fastq-to-cool-hicup-cooler.ga",
}


def _find_ga_files():
    if not IWC_DIR:
        return []
    return sorted(
        p
        for p in glob.glob(os.path.join(IWC_DIR, "workflows", "**", "*.ga"), recursive=True)
        if os.path.basename(p) not in _IWC_PYDANTIC_SKIP
    )


GA_FILES = _find_ga_files()


@pytest.mark.skipif(IWC_DIR is None, reason="GXFORMAT2_TEST_IWC_DIRECTORY not set")
class TestIWCPydantic:

    @pytest.fixture(
        params=GA_FILES,
        ids=[os.path.relpath(p, IWC_DIR) if IWC_DIR else p for p in GA_FILES],
    )
    def ga_workflow(self, request):
        with open(request.param) as f:
            return json.load(f)

    def test_native_validates(self, ga_workflow):
        NativeGalaxyWorkflow.model_validate(ga_workflow)

    def test_format2_validates(self, ga_workflow):
        format2_dict = from_galaxy_native(ga_workflow, tool_interface=None, json_wrapper=False)
        GalaxyWorkflow.model_validate(format2_dict)
