name: Publish gxformat2 Docs

on:
  push:	
    branches:	
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt -r dev-requirements.txt
        # Requires experimental schema sald for now...
        pip install https://github.com/jmchilton/schema_salad/archive/java_codegen_iter.zip
    - name: Build docs.
      run: |
        SKIP_JAVA=1 bash build_schema.sh
    - name: Deploy Docs
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.GH_PAT }}
        BASE_BRANCH: master
        BRANCH: gh-pages
        FOLDER: dist/schema

    #- uses: maxheld83/ghpages@v0.2.1
    #  env:
    #    BUILD_DIR: dist/schema
    #  with:
    #    GH_PAT: ${{ secrets.GH_PAT }}
