name: Publish gxformat2 Docs
on: [push, pull_request]
concurrency:
  group: docs-${{ github.ref }}
  cancel-in-progress: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt -r dev-requirements.txt
    - name: Build docs
      run: |
        SKIP_JAVA=1 SKIP_TYPESCRIPT=1 bash build_schema.sh
    - name: Deploy Docs
      if: github.event_name == 'push' && github.ref == 'refs/heads/master' && github.repository_owner == 'galaxyproject'
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.GH_PAT }}
        BASE_BRANCH: master
        BRANCH: gh-pages
        FOLDER: dist/schema

