name: TypeScript Continuous integration tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
env:
  NODE_VERSION: 17.x

jobs:

  CI:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./typescript
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
           node-version: ${{ env.NODE_VERSION }}
      - run: node --version
      - run: npm install
      - run: npm test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2.1.0
        with:
          directory: ./typescript
          fail_ci_if_error: true
          flags: unittests
          token: ${{ secrets.CODECOV_TOKEN }}
