name: TypeScript Continuous integration tests

on: [push, pull_request]

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:

  CI:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./typescript
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: typescript/package-lock.json
      - run: node --version
      - run: npm install
      - run: npm test
      - name: Upload coverage to Codecov
        if: github.repository_owner == 'galaxyproject'
        uses: codecov/codecov-action@v5
        with:
          directory: ./typescript
          fail_ci_if_error: true
          flags: unittests
          token: ${{ secrets.CODECOV_TOKEN }}
